use_frameworks!

platform :ios, '8.0'

target 'demo_SDWebImage_Example' do
  pod 'demo_SDWebImage', :path => '../'
	pod 'SDWebImage', '~> 5.0'
  target 'demo_SDWebImage_Tests' do
    inherit! :search_paths

    
  end
end
